{{- if .Values.storage.local.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hearth.fullname" . }}-data
  labels:
    {{- include "hearth.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.local.accessMode }}
  {{- if .Values.storage.local.storageClass }}
  storageClassName: {{ .Values.storage.local.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.local.size }}
{{- end }}
